language: ruby
rvm:
- 1.9.3
gemfile:
- Gemfile
env:
  global:
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=qubell-broadleaf-artifacts
  - QUBELL_TENANT=https://staging.dev.qubell.com
  - PROVIDER_TYPE=aws-ec2
  - PROVIDER_REGION=us-east-1
  - secure: hXAV7eH4FsxupLwEBlIFOjE8uIBCa+HIH7ym27eAgjWE5YUjxpXMjjnBX1LkQMpJOT0/ibOcafPsry02IVJJHs1JgCc2BsqJoSLUwoJWcoUTvPBTk/uLVxx/YKNgSwnizeV+ZbPByCugfC4XT2eEegNSXcLzmX8/rowc4R3cj54=
  - secure: YJcnXAF/2exke9O35mP2pHkQUmD0nlBvxaxM6aVmnrOez9nUSg0tYUs/oA1VNiIozdplhk5NELQjRhctvxtcO2gPrxdcNWXY7KFcTRLHNAXA2NNl/dpHDKZTe5WAnKqCctaEMiuqZhJPJSfJzW6ODHoWEZ4olt3n98NT4cOtxII=
  - secure: VNKhthrPjld8iNzLbLzxIoC1Hzh7OeYM488egKdM7mjaVjISfwKISZqNn34aqNhjVgX65/esgTCViYvEYn+ASuu1k5MY/GM4b1GB4KtwHtjZAxh9H3APGClpC2t7Ixm64zeGI4dfWw6UxFLjY9Lfm0xmwQ8OkSdsvn+NWbTmX7o=
  - secure: FSzAX/XcxWF9DIJHrMZQXcrImQWOcXrBgLZW0y+2C8spU4uyW44LZsAQikXuo8b4mrt/PXEEDc6Ppm3OpEJIibmfFwV9CyB8DDc+b0NaBWUM7YUSOTCTLXnH32ZPkLrjJ2eWY1sI/DpFVKHsxTKWxOyxF+d5gPZux528s4ihixw=
  - secure: N08u1CWvO1zrssf8MjXNEFPRArrztQyG7SO2HNW2UWwQ60GGjfPIx6cAN9/kfa0X8V8OXppVu9wU3YhbuZxSL5mpZdXXdhnA/4vnHCtFD9Siwk0x4fIVHyT8f2lHEpSazJJMjNqmQTYjXTVF/cWtVPfQOvOqcafTdCKYE8ur1l8=
  - secure: ZBWWoB1FsQ5oNmvfhBBCUdulrAlO9XWda0JczPsPWtmvGy51TVDUWSyC3gbfLsppW+C1toX2q+D1awfoIv7C8kxqCc++lpNRG1JNiG261nbz3JQJ4HQtMrnwdibp98PAs0uL39Y7Xti9/XfVmrj1tpxCUBJvDn85oKdeR+PAT3E=
  - secure: EblgkQj2xF0iFKEhfJkjBuyg3qwiPwgrMA76I2kVAHKvqrSFFjJqTqT/yOkGZqUNLqp9g4uT2NWJFQq52JSFBHdWa3iunTQtWant0ZJG76b2N3d6To6qgSqSudTjaexYxJZ4zBSImfwdSyx8wLHDbUyXNgDszdKkjpXT98xp6NM=
  - secure: Ndadimio+ivukpB0Ahq8srngPNZKmAzoRCm+qc3oE3DAVcVBldrvRaaSfyCA4VsR8yAzEnDdd9w3Lw7HDlTtyd95Iff/y9mWcpo8WO/1X23oWxxFII7iG3sOmhoryFoXhNQpBH8S8JCrZ2fEOXKUljDl0SguGl9BvXgyI6GoW1c=
  - secure: XIDcks1D9QWp+2cSA1Hh4nCZ0wnp64mkbzMEIQejay/PEv2G6kTjapOCDjWF66ROzt0tWVSbz2Ico8BHwJ/E66RqGRyDTbAY7IoMO0XV8tV+0N+bVfmlDisWHKj3zwrWBFtlGHuLqEfyB+c8k5BywEDSrTz0eDrQMkgWNgoaiUM=
  - secure: iR8G4x69LlxBnMm6Ornuhk+VkG7lpkg5MAEE8tosC7yuy+L/sU89zuKPNPAUwTWK7dmWmekytM30nuOoIBPXk5ThAitT8Nocr66Jg18vlRGJAWysBCTdxwtRtEEFl8NS8+snW9qcNucsKgZo6rEwGJ/wIK5J4ZbkJeZ0k9CIwF8=
install:
- sudo apt-get -y -q install python-pip
- sudo pip install -r test/requirements.txt
before_script:
- gem install --version 2.0.15 berkshelf --no-ri --no-rdoc
- gem install --version 0.8.9 faraday --no-ri --no-rdoc
- gem install travis-artifacts --no-ri --no-rdoc
- git submodule update --init --recursive
script: ./build.sh
