language: ruby
rvm:
- 1.9.3
gemfile:
- Gemfile
env:
  global:
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=qubell-starter-kit-artifacts
  - QUBELL_TENANT=https://express.qubell.com
  - PROVIDER_TYPE=aws-ec2
  - PROVIDER_REGION=us-east-1
  - secure: LWUbPQ0L/KywybHqWEe8zlngudB5schObJKTCPP6R2wgQO8NvaTl3yNh78lHyJP/CujFvy/swjUhY2gbumddurxpfqN/XDQdULlw+8QQ85unAuumLdOp4J7s0PHbeGUAerQya1dsAuV7ng5CJKQt1/CsjxcglNaDJRVvp7fvZns=
  - secure: hzpLXQPuVu4NJYoL4uEMM2aIilcJyC+b+HSxUUOPKyUrar0EUwzE1kyg/d4lhdwfFHbLNfL0hLMCG67PLq7YZ3x5PzRuXuFwncSBWkGe8shMVSrKv9tFmOxu3JWbK5aDi4LL2nEwhtB7dijzcs0dLG5nU/bM4TZ/Sof/VjvUcjw=
  - secure: dbxWIu/S6ZePspn6V7bSbMbIsjC6ylVA9T4MRWkM/UYfcgSd1mUV8jcjhKyukhA/g+aaDVKiFcFtRp77ODOx3lgxdJzTTG0QoQA4uMiNjQ4MMlXJTq4xzJ9AcQRzhU2URyMNWoJ+dZWXyDILzd0RuY3Psl9JdX0eB9YwDnan96s=
  - secure: AHyTfA/x1Nxcgh2TSmCAn3grGRKzh4Q0/Jvv/xcdTa+c4ThU/G0W3Cotso2HwuprenBdvFRrlDSaaKVVVmpjr/J1oNuH4RwW0l6CmGShdfBEHiacIbj1yLzaI9KpNIjv1kIUk5sDo++4E/bVz+zEC+rW48J/Bw83DJjN0JO7J4A=
  - secure: GfOSKRiS5HY3+Tc5adxbh5/xg70UHPH9P7JM1AZ7IdKCgx8qqzK50mQvPorAbXw8IHV/H7VSVM1YwKBsjtobJVXapunJhGH8UcqUnOk6bP9T7+aiuSvEIsgkJJJptssgkv+6oCMrOLka1djYRD3EHPZ6TlWTZCvt+nPSmSuY4SM=
  - secure: Q6geaM6NLyEl5uPjxDcVL6kSa22ptcmyBGrCL9scDPEWLpt+JylCRRi4mTp4uUZI8febpvFS4zEfHgAeWBe/9q+00xqbEnYInm91UQd5jo6ByR8HAUB8uPW+7cd2uyrEqlURH6ni1Goa5xF8kE9v+EqD+1CA7Df8wXptTC3NMrk=
  - secure: iVgZI4RAOq0Ei6lOjLV6mwzg7gs+4KLW73HLEtIPLJq+x8rB6sKdsDtA2XsOaW9smuZodCB9H6IZwOvFjz65thzF0Ub2e0TrCT0bip0Dt7yTteoaxkqVJYiaDHvLNfWeTRw4puk5qtfmAwsQdrclKf/SFgkS4Nwy77NhHPCqG9c=
install:
- sudo apt-get -y -q install python-pip
- sudo pip install -r test/requirements.txt
before_script:
- gem install --version 2.0.15 berkshelf --no-ri --no-rdoc
- gem install --version 0.8.9 faraday --no-ri --no-rdoc
- gem install travis-artifacts --no-ri --no-rdoc
- gem install --version 3.1.0 ridley --no-ri --no-rdoc
- gem install --version 0.3.2 varia_model --no-ri --no-rdoc
- gem install --version 2.0.5 hashie --no-ri --no-rdoc
- git submodule update --init --recursive
script: ./build.sh
